apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x4ybzdcvm-python
  janus-idp.io/tekton: x4ybzdcvm-python
  backstage.io/kubernetes-id: x4ybzdcvm-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x4ybzdcvm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
